### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'baseline-resnet50dilated-ppm_deepsup/encoder_epoch_20.pth'

### ISSUE THREAD

**Issue by IceStreams** [vidit98/graphconv#4]
Hello，thanks for your work. When I run train.py, error FileNotFoundError: [Errno 2] No such file or directory: 'Baseline - resnet50dilating-ppm_deepsup /encoder_epoch_20.pth'.Where can I find this file

**Comment by vidit98** [comment]
Hi, thank you for your interest in the work. You can find the model [here](http://sceneparsing.csail.mit.edu/model/pytorch/ade20k-resnet50dilated-ppm_deepsup/).

**Comment by Timeawayzxb** [comment]
Hi, I have downloaded the "encoder_epoch_20.pth" file you provided, this problem has been solved, but when I run train.py again, the error will still be reported as follows:
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "E:/Experiment/graphconv-master/train.py", line 364, in <module>
    main(args)
  File "E:/Experiment/graphconv-master/train.py", line 249, in main
    lss = train(segmentation_module, iterator_train, optimizers, history, epoch, par,vis,win, args)
  File "E:/Experiment/graphconv-master/train.py", line 35, in train
    batch_data = next(iterator)
  File "E:\Experiment\graphconv-master\lib\utils\data\dataloader.py", line 261, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "E:\Experiment\graphconv-master\lib\utils\data\dataloader.py", line 261, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "E:\Experiment\graphconv-master\dataset.py", line 148, in __getitem__
    assert(img.ndim == 3)
AttributeError: 'NoneType' object has no attribute 'ndim'
Is this because the data in the program was not read successfully？

**Comment by Timeawayzxb** [comment]
Hello, I have downloaded the ADE20K data set as requested, and placed all the training images (such as ADE_train_00000001.jpg) in data/ADEChallengeData2016/images/training and ground truth of segmentation (such as ADE_train_00000001_seg.png) in data/ADEChallengeData2016/annotations/training. but when I run the train.py. It report an error as follows:
  File "E:\Experiment\graphconv-master\model.py", line 60, in forward
    acc = self.pixel_acc(pred, feed_dict['seg_label'].cuda(0))
RuntimeError: CUDA error: device-side assert triggered.
I looked for this kind of error on the Internet, which should be caused by the tag crossing. Then I printed out the maximum value of the variable "feed_dict['seg_label'].cuda()", and found that the maximum value was lager than the number of class (150).
Is it because my data of ground truth is wrong，Have you ever come across the same problem?

**Comment by IceStreams** [comment]
Hello, thanks for your work. I have downloaded the ADE20K data set as requested, and placed all the training images (such as ADE_train_00000001.jpg) in data/ADEChallengeData2016/images/training and ground truth of segmentation (such as ADE_train_00000001_seg.png) in data/ADEChallengeData2016/annotations/training. but when I run the train.py. It report an error as follows:
File "E:\Experiment\graphconv-master\model.py", line 60, in forward
acc = self.pixel_acc(pred, feed_dict['seg_label'].cuda(0))
RuntimeError: CUDA error: device-side assert triggered.
I looked for this kind of error on the Internet, which should be caused by the tag crossing. Then I printed out the maximum value of the variable "feed_dict['seg_label'].cuda()", and found that the maximum value was lager than the number of class (150).
Is it because my data of ground truth is wrong，Have you ever come across the same problem?

**Comment by vidit98** [comment]
Yes, I also faced this issue once, it is generally border case which causes problem for example numbering in ground truth starts from 0 and you have started it from 1. Although it should not have occurred. What is the maximum value that you are getting when you print it?

**Comment by Timeawayzxb** [comment]
Because the training samples in your code are randomly selected, the maximum value printed will be different each time. But they're all larger than 150, like 184,169,157 etc

**Comment by IceStreams** [comment]
Because the training samples in your code are randomly selected, the maximum value printed will be different each time. But they're all larger than 150, like 184,169,157 etc. How did you solve this problem?

**Comment by IceStreams** [comment]
I compare the ADE_train_00000001.jpg file I downloaded from the ADE20K dataset with the ADE_train_00000001.jpg file that exists in your code. I find that the two are different.  Does this mean that the data set I downloaded is wrong? I downloaded the data set from [here](http://groups.csail.mit.edu/vision/datasets/ADE20K/) . it is the url you provided.

**Comment by vidit98** [comment]
There can be a possibility that the dataset has changed, you can check whether they have increased the number of classes from 150. Another thing you can check is that you are putting segmentation images in the ground truth and not the part segmented image.

**Comment by HW140701** [comment]
> Hi, thank you for your interest in the work. You can find the model [here](http://sceneparsing.csail.mit.edu/model/pytorch/ade20k-resnet50dilated-ppm_deepsup/).嗨，谢谢您对工作的兴趣。您可以[在这里](http://sceneparsing.csail.mit.edu/model/pytorch/ade20k-resnet50dilated-ppm_deepsup/)找到该模型。

The download link of the model has expired. Can you provide a new download link?
